import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import requests
import shap
import plotly.express as px
import plotly.graph_objects as go
import time
from sklearn.metrics import mean_absolute_error, r2_score
from auth.login import login
from auth.register import register
from auth.logger import log_activity
from admin.admin_panel import admin_panel
from dotenv import load_dotenv
import os

load_dotenv()
# ---------------- EXPORT SYSTEM ----------------
from io import BytesIO
from reportlab.lib.pagesizes import landscape
from math import ceil
import plotly.io as pio
from reportlab.platypus import SimpleDocTemplate, Image, Table, Paragraph, Spacer, PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


export_figs = []

# Store matplotlib charts
def show_and_store_matplotlib(fig):
    export_figs.append(fig)
    st.pyplot(fig)

# Store plotly charts
def show_and_store_plotly(fig):
    export_figs.append(fig)
    st.plotly_chart(fig, use_container_width=True)

# Convert figure to image
def fig_to_rl_image(fig, width=300, height=220):
    buf = BytesIO()

    if hasattr(fig, "savefig"):  # matplotlib
        fig.savefig(buf, format="png", bbox_inches="tight")
    else:  # plotly
        buf.write(pio.to_image(fig, format="png"))

    buf.seek(0)
    return Image(buf, width=width, height=height)

# Generate PDF (Power BI style)
def generate_full_dashboard_pdf(figs):

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape((1400, 800)))

    styles = getSampleStyleSheet()
    elements = []

    # ---------------- TITLE ----------------
    elements.append(Paragraph("⚡ Energy Dashboard Report", styles['Title']))
    elements.append(Spacer(1, 20))

    # Convert all figures to images
    images = [fig_to_rl_image(f, width=420, height=260) for f in figs]

    cols = 3
    rows = ceil(len(images) / cols)

    # ---------------- GRID BUILD ----------------
    grid = []
    for i in range(rows):
        row = images[i*cols:(i+1)*cols]
        while len(row) < cols:
            row.append("")
        grid.append(row)

    # ---------------- TABLE STYLE ----------------
    table = Table(grid, colWidths=[450, 450, 450])

    table.setStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BOX", (0, 0), (-1, -1), 1, colors.black),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ])

    elements.append(table)

    # ---------------- FOOTER ----------------
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by Streamlit AI Dashboard", styles['Normal']))

    doc.build(elements)
    buffer.seek(0)

    return buffer

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------
st.set_page_config(page_title="Energy Forecast Dashboard", layout="wide")

# --------------------------------------------------
# SESSION STATE INITIALIZE
# --------------------------------------------------
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
    st.session_state.username = None
    st.session_state.role = None

# --------------------------------------------------
# AUTHENTICATION
# --------------------------------------------------
if not st.session_state.logged_in:
    result = login()
    if result and result[0] is not None:
        st.session_state.logged_in = True
        st.session_state.username = result[0]
        st.session_state.role = result[1]
        st.rerun()
    else:
        st.warning("Please log in to access the dashboard.")
        st.stop()

# Session se username aur role lo
username = st.session_state.username
role = st.session_state.role

# ----------------------------
# ROLE BASED SIDEBAR
# ----------------------------
if role == "admin":
    st.sidebar.success("👑 Admin Access")
elif role == "analyst":
    st.sidebar.info("📊 Analyst Access")
else:
    st.sidebar.warning("👀 Viewer Access")

# ----------------------------
# LOGOUT BUTTON
# ----------------------------
if st.sidebar.button("🚪 Logout"):
    st.session_state.logged_in = False
    st.session_state.username = None
    st.session_state.role = None
    st.rerun()

# ----------------------------
# SIDEBAR NAVIGATION
# ----------------------------
menu = st.sidebar.selectbox(
    "Navigation",
    ["Dashboard", "Admin Panel", "Register"]
)

# ----------------------------
# DASHBOARD PAGE
# ----------------------------
if menu == "Dashboard":

    st.title("⚡ Energy Demand Forecast Dashboard")

    # --------------------------------------------------
    # REAL TIME DASHBOARD
    # --------------------------------------------------
    auto_refresh = st.sidebar.checkbox("🔄 Live Monitoring")

    if auto_refresh:
        time.sleep(30)
        st.rerun()

    # --------------------------------------------------
    # API SETTINGS
    # --------------------------------------------------
    API_KEY = os.getenv("OPENWEATHER_API_KEY")
    CITY = os.getenv("CITY")

    # --------------------------------------------------
    # LOAD MODEL
    # --------------------------------------------------
    @st.cache_resource
    def load_model():
        return joblib.load("models/xgboost_energy_model_v2.pkl")

    model = load_model()

    features = model.get_booster().feature_names

    explainer = shap.TreeExplainer(model)

    # --------------------------------------------------
    # WEATHER API
    # --------------------------------------------------
    def get_weather():
        try:
            url = f"https://api.openweathermap.org/data/2.5/weather?q={CITY}&appid={API_KEY}&units=metric"
            r = requests.get(url)
            data = r.json()
            weather = {
                "temp": data["main"]["temp"],
                "humidity": data["main"]["humidity"],
                "wind_speed": data["wind"]["speed"],
                "clouds": data["clouds"]["all"]
            }
        except:
            weather = {
                "temp": 20,
                "humidity": 50,
                "wind_speed": 5,
                "clouds": 20
            }
        return weather

    weather = get_weather()

    # --------------------------------------------------
    # WEATHER KPI
    # --------------------------------------------------
    st.subheader("🌦 Live Weather")

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("🌡 Temperature", f"{weather['temp']} °C")
    c2.metric("💧 Humidity", f"{weather['humidity']} %")
    c3.metric("🌬 Wind Speed", f"{weather['wind_speed']} m/s")
    c4.metric("☁ Cloud Cover", f"{weather['clouds']} %")

    # --------------------------------------------------
    # SIDEBAR INPUTS
    # --------------------------------------------------
    st.sidebar.header("⚙ Prediction Inputs")

    load_lag_1 = st.sidebar.number_input("Previous Hour Load", 25000)
    load_lag_24 = st.sidebar.number_input("Load 24 Hours Ago", 26000)
    load_lag_168 = st.sidebar.number_input("Load 7 Days Ago", 25500)
    solar_forecast = st.sidebar.number_input("Solar Forecast", 500)
    wind_forecast = st.sidebar.number_input("Wind Forecast", 600)

    # --------------------------------------------------
    # FEATURE BUILDER
    # --------------------------------------------------
    def build_features(hour):
        df = pd.DataFrame(np.zeros((1, len(features))), columns=features)
        now = datetime.now()
        df["hour_x"] = hour
        df["day_x"] = now.day
        df["month_x"] = now.month
        df["weekday_x"] = now.weekday()
        df["is_weekend_x"] = int(now.weekday() >= 5)
        df["load_lag_1"] = load_lag_1
        df["load_lag_24"] = load_lag_24
        df["load_lag_168"] = load_lag_168
        df["forecast solar day ahead"] = solar_forecast
        df["forecast wind onshore day ahead"] = wind_forecast
        df["generation solar"] = solar_forecast
        df["generation wind onshore"] = wind_forecast
        df["temp"] = weather["temp"]
        df["humidity"] = weather["humidity"]
        df["wind_speed"] = weather["wind_speed"]
        return df

    # --------------------------------------------------
    # LIVE PREDICTION
    # --------------------------------------------------
    st.subheader("🔮 Live Prediction")

    hour = st.slider("Select Hour", 0, 23, 12)

    if st.button("Predict Load"):
        if role not in ["admin", "analyst"]:
            st.error("🚫 Only Admin or Analyst can run predictions")
            st.stop()

        log_activity(username, "Prediction_run")

        X = build_features(hour)
        pred = model.predict(X)[0]
        st.success(f"⚡ Predicted Load: {pred:,.2f} MW")

        # INTERACTIVE GAUGE
        fig = go.Figure(go.Indicator(
            mode="gauge+number",
            value=pred,
            title={'text': "Energy Demand"},
            gauge={
                'axis': {'range': [None, 60000]},
                'bar': {'color': "orange"},
                'steps': [
                    {'range': [0, 20000], 'color': "green"},
                    {'range': [20000, 40000], 'color': "yellow"},
                    {'range': [40000, 60000], 'color': "red"}
                ]
            }
        ))
        show_and_store_plotly(fig)

        # SHAP explanation
        shap_values = explainer.shap_values(X)
        st.subheader("🔍 Prediction Explanation")
        fig = plt.figure()
        shap.plots.waterfall(
            shap.Explanation(
                values=shap_values[0],
                base_values=explainer.expected_value,
                data=X.iloc[0],
                feature_names=X.columns
            ),
            show=False
        )
        show_and_store_matplotlib(fig)

        # Top feature impact (reason)
        st.subheader("🔍 Key Drivers Behind Prediction")

        top_features = sorted(
            zip(X.columns, shap_values[0]),
            key=lambda x: abs(x[1]),
            reverse=True
        )[:3]

        for f, v in top_features:
            st.write(f"➡ {f}: impact {v:.2f}")

    # --------------------------------------------------
    # 24 HOUR FORECAST
    # --------------------------------------------------
    st.subheader("📊 24 Hour Forecast")

    hours = list(range(24))
    preds = []
    for h in hours:
        X = build_features(h)
        p = model.predict(X)[0]
        preds.append(p)

    forecast_df = pd.DataFrame({"Hour": hours, "Load": preds})

    fig = px.line(forecast_df, x="Hour", y="Load", markers=True, title="Next 24 Hour Energy Forecast")
    show_and_store_plotly(fig)
    st.dataframe(forecast_df, use_container_width=True)

    # --------------------------------------------------
    # Peak Demand Insight
    # --------------------------------------------------
    peak_hour = forecast_df.loc[forecast_df["Load"].idxmax()]
    peak_load = forecast_df["Load"].max()

    st.subheader("⚡ Peak Demand Insight")
    st.info(
        f"Highest demand expected at Hour {int(peak_hour['Hour'])} "
        f"with {peak_hour['Load']:,.0f} MW"
    )

    # --------------------------------------------------
    # Demand Alert System
    # --------------------------------------------------
    st.subheader("🚨 Demand Alert System")

    if peak_load > 38000:
        st.error("⚠ High Demand Expected — Grid Load May Surge")
    elif peak_load > 32000:
        st.warning("⚡ Moderate Demand Expected")
    else:
        st.success("✅ Demand Within Normal Range") 

    # --------------------------------------------------
    # 🤖 AI Decision Engine (Advanced)
    # --------------------------------------------------
    st.subheader("🧠 AI Decision Engine")

    # Dynamic thresholds
    avg_load = forecast_df["Load"].mean()
    std_load = forecast_df["Load"].std()

    high_threshold = avg_load + std_load
    moderate_threshold = avg_load + (0.5 * std_load)

    # Current prediction (selected hour)
    current_pred = forecast_df["Load"].iloc[hour]

    # Decision logic
    if current_pred > high_threshold:
        st.error("⚠ HIGH RISK: Grid overload possible")
        action = "Increase renewable generation / apply load balancing"
    elif current_pred > moderate_threshold:
        st.warning("⚡ MODERATE RISK: Monitor grid closely")
        action = "Optimize energy distribution"
    else:
        st.success("✅ LOW RISK: System stable")
        action = "No action required"

    # Show recommendation
    st.info(f"💡 Recommended Action: {action}")

    # --------------------------------------------------
    # ENERGY SYSTEM KPI
    # --------------------------------------------------
    st.subheader("📊 Energy System Overview")

    k1, k2, k3, k4 = st.columns(4)
    current_load = forecast_df["Load"].iloc[hour]
    peak_load = forecast_df["Load"].max()
    min_load = forecast_df["Load"].min()
    renewable = solar_forecast + wind_forecast

    k1.metric("⚡ Current Demand", f"{current_load:,.0f} MW")
    k2.metric("📈 Peak Load", f"{peak_load:,.0f} MW")
    k3.metric("📉 Minimum Load", f"{min_load:,.0f} MW")
    k4.metric("🌞 Renewable Forecast", f"{renewable} MW")

    # --------------------------------------------------
    # Renewable Energy Contribution
    # --------------------------------------------------
    st.subheader("🌱 Renewable Energy Contribution")

    renewable_total = solar_forecast + wind_forecast
    total_energy = current_load
    renewable_percent = (renewable_total / total_energy) * 100 if total_energy != 0 else 0
    st.metric("Renewable Share", f"{renewable_percent:.1f}%")

    # --------------------------------------------------
    # Renewable vs Demand
    # --------------------------------------------------
    st.subheader("🌱 Renewable vs Demand")

    energy_df = pd.DataFrame({
        "Source": ["Solar", "Wind", "Total Demand"],
        "Value": [solar_forecast, wind_forecast, current_load]
    })
    fig = px.bar(energy_df, x="Source", y="Value", title="Energy Mix vs Demand")
    show_and_store_plotly(fig)

    # --------------------------------------------------
    # AI Energy Insights
    # --------------------------------------------------
    st.subheader("🤖 AI Energy Insights")

    insight = f"""
    Peak demand expected around {int(peak_hour['Hour'])}:00.

    Current renewable contribution is {renewable_percent:.1f}% of total demand.

    Higher temperature ({weather['temp']}°C) may increase electricity consumption.
    """
    st.info(insight)

    # --------------------------------------------------
    # HOURLY HEATMAP
    # --------------------------------------------------
    st.subheader("🔥 Hourly Energy Demand Heatmap")

    heatmap_data = forecast_df.copy()
    heatmap_data["Day"] = "Today"
    pivot = heatmap_data.pivot(index="Day", columns="Hour", values="Load")

    fig = plt.figure(figsize=(18, 3))
    sns.heatmap(pivot, cmap="coolwarm", annot=True, fmt=".0f", linewidths=0.5, annot_kws={"rotation": 90})
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # WEEKLY HEATMAP
    # --------------------------------------------------
    st.subheader("🔥 Weekly Energy Demand Heatmap")

    days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    heatmap_matrix = []

    for d in range(7):
        daily_load = []
        for h in range(24):
            X = build_features(h)
            p = model.predict(X)[0]
            daily_load.append(p)
        heatmap_matrix.append(daily_load)

    heatmap_df = pd.DataFrame(heatmap_matrix, index=days, columns=list(range(24)))

    fig = plt.figure(figsize=(18, 5))
    sns.heatmap(heatmap_df, cmap="coolwarm", annot=True, fmt=".0f", linewidths=0.3, annot_kws={"rotation": 90})
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # GLOBAL FEATURE IMPORTANCE
    # --------------------------------------------------
    st.subheader("🌍 Global Feature Importance")

    sample = pd.DataFrame(np.random.rand(200, len(features)), columns=features)
    shap_vals = explainer.shap_values(sample)

    fig = plt.figure()
    shap.summary_plot(shap_vals, sample, show=False)
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # HISTORICAL DATA
    # --------------------------------------------------
    @st.cache_data
    def load_data():
        return pd.read_csv("data/processed/merged_energy_weather.csv")

    data = load_data()
    data = data.drop_duplicates()
    data = data.dropna(subset=["total load actual"])

    if len(data) > 2000:
        data = data.sample(2000)

    # --------------------------------------------------
    # ACTUAL VS PREDICTED
    # --------------------------------------------------
    st.subheader("📉 Actual vs Predicted")

    X_hist = data[features].fillna(0)
    y_actual = data["total load actual"]
    y_pred = model.predict(X_hist)

    fig = plt.figure()
    plt.plot(y_actual.values[:200], label="Actual")
    plt.plot(y_pred[:200], label="Predicted", alpha=0.9)
    plt.legend()
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # Model Performance KPI
    # --------------------------------------------------
    eval_df = pd.DataFrame({"actual": y_actual, "pred": y_pred}).dropna()
    mae = mean_absolute_error(eval_df["actual"], eval_df["pred"])
    r2 = r2_score(eval_df["actual"], eval_df["pred"])

    st.subheader("📊 Model Performance")
    m1, m2 = st.columns(2)
    m1.metric("MAE", f"{mae:,.2f}")
    m2.metric("R² Score", f"{r2:.3f}")

    # --------------------------------------------------
    # ERROR DISTRIBUTION
    # --------------------------------------------------
    st.subheader("📊 Error Distribution")

    errors = y_actual - y_pred
    fig = plt.figure()
    plt.hist(errors, bins=40)
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # FORECAST Confidence Range
    # --------------------------------------------------
    st.subheader("📉 Forecast Confidence Range")

    std = np.std(errors)
    upper = forecast_df["Load"] + std
    lower = forecast_df["Load"] - std

    fig = plt.figure()
    plt.plot(forecast_df["Hour"], forecast_df["Load"], label="Prediction")
    plt.fill_between(forecast_df["Hour"], lower, upper, alpha=0.3, label="Confidence Range")
    plt.legend()
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # RESIDUAL PLOT
    # --------------------------------------------------
    st.subheader("📈 Residual Analysis")

    fig = plt.figure()
    plt.scatter(y_pred, errors)
    plt.xlabel("Predicted")
    plt.ylabel("Residual")
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # LOAD VS TEMP
    # --------------------------------------------------
    st.subheader("🌡 Load vs Temperature")

    fig = plt.figure()
    plt.scatter(data["temp"], data["total load actual"])
    plt.xlabel("Temperature")
    plt.ylabel("Load")
    show_and_store_matplotlib(fig)

    # --------------------------------------------------
    # Correlation Heatmap
    # --------------------------------------------------
    st.subheader("📊 Correlation Heatmap")

    corr = data.corr(numeric_only=True)
    fig = plt.figure(figsize=(12, 8))
    sns.heatmap(corr, cmap="coolwarm", annot=False)
    show_and_store_matplotlib(fig)



elif menu == "Register":
    if role == "admin":
        register()
    else:
        st.error("Only admin can register users")

elif menu == "Admin Panel":
    if role == "admin":
        admin_panel()
    else:
        st.error("Access denied")



# --------------------------------------------------
# EXPORT FULL DASHBOARD
# --------------------------------------------------
st.subheader("📥 Export Full Dashboard")

if st.button("📊 Download Power BI Style Report"):

    if len(export_figs) == 0:
        st.warning("No charts to export")
    else:
        pdf = generate_full_dashboard_pdf(export_figs)

        st.download_button(
            "⬇ Download Report",
            pdf,
            "full_dashboard.pdf",
            "application/pdf"
        )